#!/bin/sh

# テスト結果ページを閲覧するためのWEBサーバ
# script/run-test実行後にこのスクリプトを起動する
#
# 現状あるバグとして、常時サーバを立ち上げておいた状態にしておくと、
# テスト実行後にアクセスするとサーバエラーを起こす
# 
# todo: HTTPサーバを常時立ち上げておけるようにする
# todo: OSXのMarvericks以外では動作確認していない

script_dir=$(cd $(dirname $0); pwd)
cd "$script_dir/.."
report_dir="`pwd`/sdk/build/reports/instrumentTests/connected"
cd $report_dir

python -m SimpleHTTPServer
