#!/bin/sh

script_dir=$(cd $(dirname $0); pwd)
cd "$script_dir/.."
./gradlew connectedCheck

if [ $(uname) == 'Darwin' ]
then
  report="$script_dir/../sdk/build/reports/instrumentTests/connected/index.html"
  open "$report"
fi
