#!/bin/sh

script_dir=$(cd $(dirname $0); pwd)
cd "$script_dir/.."

if [ $(uname) == 'Darwin' ]
then
  report="$script_dir/../sdk/build/reports/instrumentTests/connected/index.html"
  open "$report"
else
  echo 'sorry, MacOSX support only...'
fi
